name: Deploy Infrastructure and ArgoCD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: prod-eks-cluster
      AWS_REGION: us-east-1

    steps:
      - uses: actions/checkout@v4
      - run: chmod +x scripts/*.sh

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: bash scripts/check_install_tools.sh

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=bonny-terraform-state-prod" \
            -backend-config="key=eks/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="encrypt=true" \
            # -backend-config="dynamodb_table=terraform-locks"

      - name: Apply Terraform
        id: apply
        run: bash scripts/terraform_apply.sh

      - name: Update kubeconfig
        run: bash scripts/update_kubeconfig.sh ${{ env.CLUSTER_NAME }} ${{ env.AWS_REGION }}

      - name: Install ArgoCD
        run: bash scripts/install_argocd.sh

  cleanup:
    runs-on: ubuntu-latest
    needs: deploy
    if: failure()  # only runs if deploy fails
    env:
      AWS_REGION: us-east-1

    steps:
      - uses: actions/checkout@v4
      - run: chmod +x scripts/*.sh
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init (for cleanup)
        run: |
          terraform init \
            -backend-config="bucket=bonny-terraform-state-prod" \
            -backend-config="key=eks/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="encrypt=true" \
            # -backend-config="dynamodb_table=terraform-locks"

      - name: Terraform Destroy
        run: bash scripts/terraform_destroy.sh
